### ISSUE TITLE
responsive resizing on card?

### ISSUE THREAD

**Issue by frumbert** [wiredjs/wired-elements#39]
When I resize my page, the card doesn't resize dynamically. Can I trigger it somehow?

```html
	<body>
		<main>
			<wired-card elevation="2">Here's my content</wired-card>
		</main>
	</body>	
```
and some css to show responsiveness
```css
	body,html { height:100vh;}
	body{display:flex;}
	main{flex:1;position:relative}
	wired-card{position:absolute;top:10px;left:10px;width:calc(100%-20px);height:calc(100%-20px)}
```

I didn't see any particular handlers for observing or responding to resize events on these components - perhaps I'm missing something?
